import type { Metadata } from "next";
import { Knewave } from "next/font/google";
import "./globals.css";

export const knewave = Knewave({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={knewave.className}>
        {children}
      </body>
    </html>
  );
}
